logging:
  path: /data/log/leisure-member

server:
  servlet:
    context-path: /leisure-member

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.cache.use_second_level_cache: false
      hibernate.show_sql: true
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.enable_lazy_load_no_trans: true
      hibernate.ejb.interceptor: com.github.hicolors.leisure.common.jpa.customiz.interceptor.BizInterceptor

warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2

platform:
  creator:
    default-role: 100010
