logging:
  path: /data/log/leisure-member
  config: classpath:logback.xml

server:
  servlet:
    context-path: /leisure-member

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    druid:
      initial-size: 8
      min-idle: 8
      max-active: 80
      async-init: true
      max-wait: 60000
      use-unfair-lock: true
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      validation-query: select 'x'
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      max-pool-prepared-statement-per-connection-size: -1
      max-open-prepared-statements: -1
      pool-prepared-statements: false
      filters: stat,wall,slf4j
      filter:
        stat:
          slow-sql-millis: 0
          log-slow-sql: true
        wall:
          config:
            truncate-allow: false
            alter-table-allow: false
            drop-table-allow: false
            condition-and-alway-true-allow: true
          enabled: true
      stat-view-servlet:
        login-password: leisure
        login-username: leisure
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    open-in-view: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.show_sql: false
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.enable_lazy_load_no_trans: true
      hibernate.session_factory.interceptor: com.github.life.lab.leisure.common.jpa.customiz.interceptor.BizInterceptor
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.use_structured_entries: true
      hibernate.cache.region.factory_class: com.github.life.lab.leisure.member.application.configuration.ColorsRedissonRegionFactory
      hibernate.cache.region_prefix: cache_

warning:
  dingtalk: https://oapi.dingtalk.com/robot/send?access_token=099551a192492077a922a5d1aa7e1a060b0fd18890f021c0e4298013d4dcb5c2


default:
  value:
    ## 用户默认角色
    member-role: xxx
    ## 员工默认角色
    platform-member-role: xxx
    ## 平台创建者默认角色
    platform-creator-role: xxx