spring:
  datasource:
    url: jdbc:mysql://47.105.97.16:3306/leisure_member?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root